### ISSUE TITLE
Corectare tema 1 (v1)

### ISSUE THREAD

**Issue by iulianaciobanitei** [adyoblu/JocTable#1]
- [x] De scos de pe background imaginea cu tablele. Poate fi lăsată doar pe o singură pagină, dar textul este greu de citit.
- [x] "3.	Interfață grafică atractivă și ușor de utilizat" merge la cerințele non-funcționale
- [x] "10.	Implementarea unui sistem de notificare pentru a alerta jucătorii atunci când este rândul lor să joace;"  ar trebui reformulat în ceva de felul : "Posiblitatea de notificare pentru a alerta jucătorii atunci când este rândul lor să realizeze o acțiune"

**Comment by adyoblu** [comment]
- Am sters imaginea de background cu table pentru a fi mai usor de citit textul
- aceeasi cerinta am folosit-o la cerintele non-functionale "10.	Grafică: Jocul trebuie să aibă o grafică atractivă, fără a fi prea încărcată." si am adaugat la cerinte functionale "3.	Posibilitatea de a afisa un mesaj de eroare in cazul in care utilizatorul nu este gasit in baza de date;"
- reformularea cerintei a fost realizata in "Posiblitatea de notificare pentru a alerta jucătorii atunci când este rândul lor să realizeze o acțiune"

**Comment by adyoblu** [comment]
1. Am sters imaginea de background cu table pentru a fi mai usor de citit textul
2. aceeasi cerinta am folosit-o la cerintele non-functionale "10. Grafică: Jocul trebuie să aibă o grafică atractivă, fără a fi prea încărcată." si am adaugat la cerinte functionale "3. Posibilitatea de a afisa un mesaj de eroare in cazul in care utilizatorul nu este gasit in baza de date;"
3. reformularea cerintei a fost realizata in "Posiblitatea de notificare pentru a alerta jucătorii atunci când este rândul lor să realizeze o acțiune"
